/**
 * Schema.org Vocabulary Items
 *
 * Key classes and properties from Schema.org for Monaco editor auto-completion.
 * Covers the most commonly used types for structured data on the web.
 */
import type { VocabularyItem } from '../../../types/domain'

const SCHEMA = 'http://schema.org/'

// ─── Classes ──────────────────────────────────────────────────────

const SCHEMA_CLASSES: VocabularyItem[] = [
  {
    iri: `${SCHEMA}Thing`,
    prefixedName: 'schema:Thing',
    label: 'Thing',
    kind: 'class',
    description: 'The most generic type of item',
    position: 'object',
  },
  {
    iri: `${SCHEMA}CreativeWork`,
    prefixedName: 'schema:CreativeWork',
    label: 'CreativeWork',
    kind: 'class',
    description: 'The most generic kind of creative work',
    position: 'object',
  },
  {
    iri: `${SCHEMA}Article`,
    prefixedName: 'schema:Article',
    label: 'Article',
    kind: 'class',
    description: 'An article, such as a news article or piece of investigative report',
    position: 'object',
  },
  {
    iri: `${SCHEMA}BlogPosting`,
    prefixedName: 'schema:BlogPosting',
    label: 'BlogPosting',
    kind: 'class',
    description: 'A blog post',
    position: 'object',
  },
  {
    iri: `${SCHEMA}NewsArticle`,
    prefixedName: 'schema:NewsArticle',
    label: 'NewsArticle',
    kind: 'class',
    description: 'A NewsArticle is an article whose content reports news',
    position: 'object',
  },
  {
    iri: `${SCHEMA}Book`,
    prefixedName: 'schema:Book',
    label: 'Book',
    kind: 'class',
    description: 'A book',
    position: 'object',
  },
  {
    iri: `${SCHEMA}Movie`,
    prefixedName: 'schema:Movie',
    label: 'Movie',
    kind: 'class',
    description: 'A movie',
    position: 'object',
  },
  {
    iri: `${SCHEMA}MusicRecording`,
    prefixedName: 'schema:MusicRecording',
    label: 'MusicRecording',
    kind: 'class',
    description: 'A music recording (track), usually a single song',
    position: 'object',
  },
  {
    iri: `${SCHEMA}Event`,
    prefixedName: 'schema:Event',
    label: 'Event',
    kind: 'class',
    description: 'An event happening at a certain time and location',
    position: 'object',
  },
  {
    iri: `${SCHEMA}Person`,
    prefixedName: 'schema:Person',
    label: 'Person',
    kind: 'class',
    description: 'A person (alive, dead, undead, or fictional)',
    position: 'object',
  },
  {
    iri: `${SCHEMA}Organization`,
    prefixedName: 'schema:Organization',
    label: 'Organization',
    kind: 'class',
    description: 'An organization such as a school, NGO, corporation, club, etc.',
    position: 'object',
  },
  {
    iri: `${SCHEMA}LocalBusiness`,
    prefixedName: 'schema:LocalBusiness',
    label: 'LocalBusiness',
    kind: 'class',
    description: 'A particular physical business or branch of an organization',
    position: 'object',
  },
  {
    iri: `${SCHEMA}Place`,
    prefixedName: 'schema:Place',
    label: 'Place',
    kind: 'class',
    description: 'Entities that have a somewhat fixed, physical extension',
    position: 'object',
  },
  {
    iri: `${SCHEMA}Product`,
    prefixedName: 'schema:Product',
    label: 'Product',
    kind: 'class',
    description: 'Any offered product or service',
    position: 'object',
  },
  {
    iri: `${SCHEMA}Offer`,
    prefixedName: 'schema:Offer',
    label: 'Offer',
    kind: 'class',
    description: 'An offer to transfer some rights to an item or to provide a service',
    position: 'object',
  },
  {
    iri: `${SCHEMA}Action`,
    prefixedName: 'schema:Action',
    label: 'Action',
    kind: 'class',
    description: 'An action performed by a direct agent and indirect participants',
    position: 'object',
  },
  {
    iri: `${SCHEMA}FAQPage`,
    prefixedName: 'schema:FAQPage',
    label: 'FAQPage',
    kind: 'class',
    description: 'A FAQPage is a WebPage presenting one or more "Frequently asked questions"',
    position: 'object',
  },
  {
    iri: `${SCHEMA}WebSite`,
    prefixedName: 'schema:WebSite',
    label: 'WebSite',
    kind: 'class',
    description: 'A WebSite is a set of related web pages',
    position: 'object',
  },
  {
    iri: `${SCHEMA}WebPage`,
    prefixedName: 'schema:WebPage',
    label: 'WebPage',
    kind: 'class',
    description: 'A web page',
    position: 'object',
  },
  {
    iri: `${SCHEMA}ImageObject`,
    prefixedName: 'schema:ImageObject',
    label: 'ImageObject',
    kind: 'class',
    description: 'An image file',
    position: 'object',
  },
  {
    iri: `${SCHEMA}VideoObject`,
    prefixedName: 'schema:VideoObject',
    label: 'VideoObject',
    kind: 'class',
    description: 'A video file',
    position: 'object',
  },
  {
    iri: `${SCHEMA}AggregateRating`,
    prefixedName: 'schema:AggregateRating',
    label: 'AggregateRating',
    kind: 'class',
    description: 'The average rating based on multiple ratings or reviews',
    position: 'object',
  },
  {
    iri: `${SCHEMA}Review`,
    prefixedName: 'schema:Review',
    label: 'Review',
    kind: 'class',
    description: 'A review of an item',
    position: 'object',
  },
  {
    iri: `${SCHEMA}Brand`,
    prefixedName: 'schema:Brand',
    label: 'Brand',
    kind: 'class',
    description:
      'A brand is a name used by an organization or business person for labeling a product',
    position: 'object',
  },
  {
    iri: `${SCHEMA}PostalAddress`,
    prefixedName: 'schema:PostalAddress',
    label: 'PostalAddress',
    kind: 'class',
    description: 'The mailing address',
    position: 'object',
  },
  {
    iri: `${SCHEMA}GeoCoordinates`,
    prefixedName: 'schema:GeoCoordinates',
    label: 'GeoCoordinates',
    kind: 'class',
    description: 'The geographic coordinates of a place or event',
    position: 'object',
  },
  {
    iri: `${SCHEMA}ContactPoint`,
    prefixedName: 'schema:ContactPoint',
    label: 'ContactPoint',
    kind: 'class',
    description: 'A contact point for a person or organization',
    position: 'object',
  },
  {
    iri: `${SCHEMA}Question`,
    prefixedName: 'schema:Question',
    label: 'Question',
    kind: 'class',
    description: 'A specific question',
    position: 'object',
  },
  {
    iri: `${SCHEMA}Answer`,
    prefixedName: 'schema:Answer',
    label: 'Answer',
    kind: 'class',
    description: 'An answer offered to a question',
    position: 'object',
  },
  {
    iri: `${SCHEMA}OpeningHoursSpecification`,
    prefixedName: 'schema:OpeningHoursSpecification',
    label: 'OpeningHoursSpecification',
    kind: 'class',
    description: 'A structured value providing information about the opening hours of a place',
    position: 'object',
  },
  {
    iri: `${SCHEMA}CollegeOrUniversity`,
    prefixedName: 'schema:CollegeOrUniversity',
    label: 'CollegeOrUniversity',
    kind: 'class',
    description: 'A college, university, or other third-level educational institution',
    position: 'object',
  },
  {
    iri: `${SCHEMA}VirtualLocation`,
    prefixedName: 'schema:VirtualLocation',
    label: 'VirtualLocation',
    kind: 'class',
    description: 'An online or virtual location for attending an event',
    position: 'object',
  },
]

// ─── Properties ───────────────────────────────────────────────────

const SCHEMA_PROPERTIES: VocabularyItem[] = [
  // Common properties
  {
    iri: `${SCHEMA}name`,
    prefixedName: 'schema:name',
    label: 'name',
    kind: 'property',
    description: 'The name of the item',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}description`,
    prefixedName: 'schema:description',
    label: 'description',
    kind: 'property',
    description: 'A description of the item',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}url`,
    prefixedName: 'schema:url',
    label: 'url',
    kind: 'property',
    description: 'URL of the item',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}image`,
    prefixedName: 'schema:image',
    label: 'image',
    kind: 'property',
    description: 'An image of the item',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}sameAs`,
    prefixedName: 'schema:sameAs',
    label: 'sameAs',
    kind: 'property',
    description: "URL of a reference Web page that unambiguously indicates the item's identity",
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}identifier`,
    prefixedName: 'schema:identifier',
    label: 'identifier',
    kind: 'property',
    description: 'The identifier property represents any kind of identifier for any kind of Thing',
    position: 'predicate',
  },
  // CreativeWork properties
  {
    iri: `${SCHEMA}author`,
    prefixedName: 'schema:author',
    label: 'author',
    kind: 'property',
    description: 'The author of this content or rating',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}dateCreated`,
    prefixedName: 'schema:dateCreated',
    label: 'dateCreated',
    kind: 'property',
    description: 'The date on which the CreativeWork was created',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}dateModified`,
    prefixedName: 'schema:dateModified',
    label: 'dateModified',
    kind: 'property',
    description: 'The date on which the CreativeWork was most recently modified',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}datePublished`,
    prefixedName: 'schema:datePublished',
    label: 'datePublished',
    kind: 'property',
    description: 'Date of first broadcast/publication',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}headline`,
    prefixedName: 'schema:headline',
    label: 'headline',
    kind: 'property',
    description: 'Headline of the article',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}text`,
    prefixedName: 'schema:text',
    label: 'text',
    kind: 'property',
    description: 'The textual content of this CreativeWork',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}publisher`,
    prefixedName: 'schema:publisher',
    label: 'publisher',
    kind: 'property',
    description: 'The publisher of the creative work',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}mainEntity`,
    prefixedName: 'schema:mainEntity',
    label: 'mainEntity',
    kind: 'property',
    description: 'Indicates the primary entity described in some page or other CreativeWork',
    position: 'predicate',
  },
  // Offer properties
  {
    iri: `${SCHEMA}price`,
    prefixedName: 'schema:price',
    label: 'price',
    kind: 'property',
    description: 'The offer price of a product',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}priceCurrency`,
    prefixedName: 'schema:priceCurrency',
    label: 'priceCurrency',
    kind: 'property',
    description: 'The currency of the price (ISO 4217 format)',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}offers`,
    prefixedName: 'schema:offers',
    label: 'offers',
    kind: 'property',
    description: 'An offer to provide this item',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}availability`,
    prefixedName: 'schema:availability',
    label: 'availability',
    kind: 'property',
    description: 'The availability of this item',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}priceValidUntil`,
    prefixedName: 'schema:priceValidUntil',
    label: 'priceValidUntil',
    kind: 'property',
    description: 'The date after which the price is no longer available',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}validFrom`,
    prefixedName: 'schema:validFrom',
    label: 'validFrom',
    kind: 'property',
    description: 'The date when the item becomes valid',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}validThrough`,
    prefixedName: 'schema:validThrough',
    label: 'validThrough',
    kind: 'property',
    description: 'The date after when the item is not valid',
    position: 'predicate',
  },
  // Rating properties
  {
    iri: `${SCHEMA}aggregateRating`,
    prefixedName: 'schema:aggregateRating',
    label: 'aggregateRating',
    kind: 'property',
    description: 'The overall rating, based on a collection of reviews or ratings',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}ratingValue`,
    prefixedName: 'schema:ratingValue',
    label: 'ratingValue',
    kind: 'property',
    description: 'The rating for the content',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}reviewCount`,
    prefixedName: 'schema:reviewCount',
    label: 'reviewCount',
    kind: 'property',
    description: 'The count of total number of reviews',
    position: 'predicate',
  },
  // Address properties
  {
    iri: `${SCHEMA}streetAddress`,
    prefixedName: 'schema:streetAddress',
    label: 'streetAddress',
    kind: 'property',
    description: 'The street address (e.g., 1600 Amphitheatre Pkwy)',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}addressLocality`,
    prefixedName: 'schema:addressLocality',
    label: 'addressLocality',
    kind: 'property',
    description: 'The locality in which the street address is, and which is in the region',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}addressRegion`,
    prefixedName: 'schema:addressRegion',
    label: 'addressRegion',
    kind: 'property',
    description: 'The region in which the locality is, and which is in the country',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}postalCode`,
    prefixedName: 'schema:postalCode',
    label: 'postalCode',
    kind: 'property',
    description: 'The postal code',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}addressCountry`,
    prefixedName: 'schema:addressCountry',
    label: 'addressCountry',
    kind: 'property',
    description: 'The country (ISO 3166-1 alpha-2 country code)',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}address`,
    prefixedName: 'schema:address',
    label: 'address',
    kind: 'property',
    description: 'Physical address of the item',
    position: 'predicate',
  },
  // Contact properties
  {
    iri: `${SCHEMA}telephone`,
    prefixedName: 'schema:telephone',
    label: 'telephone',
    kind: 'property',
    description: 'The telephone number',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}email`,
    prefixedName: 'schema:email',
    label: 'email',
    kind: 'property',
    description: 'Email address',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}logo`,
    prefixedName: 'schema:logo',
    label: 'logo',
    kind: 'property',
    description: 'An associated logo',
    position: 'predicate',
  },
  // Geo properties
  {
    iri: `${SCHEMA}geo`,
    prefixedName: 'schema:geo',
    label: 'geo',
    kind: 'property',
    description: 'The geo coordinates of the place',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}latitude`,
    prefixedName: 'schema:latitude',
    label: 'latitude',
    kind: 'property',
    description: 'The latitude of a location',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}longitude`,
    prefixedName: 'schema:longitude',
    label: 'longitude',
    kind: 'property',
    description: 'The longitude of a location',
    position: 'predicate',
  },
  // Event properties
  {
    iri: `${SCHEMA}startDate`,
    prefixedName: 'schema:startDate',
    label: 'startDate',
    kind: 'property',
    description: 'The start date and time of the item (in ISO 8601 date format)',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}endDate`,
    prefixedName: 'schema:endDate',
    label: 'endDate',
    kind: 'property',
    description: 'The end date and time of the item (in ISO 8601 date format)',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}location`,
    prefixedName: 'schema:location',
    label: 'location',
    kind: 'property',
    description: 'The location of, for example, where an event is happening',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}performer`,
    prefixedName: 'schema:performer',
    label: 'performer',
    kind: 'property',
    description: 'A performer at the event',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}organizer`,
    prefixedName: 'schema:organizer',
    label: 'organizer',
    kind: 'property',
    description: 'An organizer of an Event',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}eventStatus`,
    prefixedName: 'schema:eventStatus',
    label: 'eventStatus',
    kind: 'property',
    description: 'An eventStatus of an event represents its status',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}eventAttendanceMode`,
    prefixedName: 'schema:eventAttendanceMode',
    label: 'eventAttendanceMode',
    kind: 'property',
    description:
      'The eventAttendanceMode of an event indicates whether it occurs online, offline, or a mix',
    position: 'predicate',
  },
  // Person properties
  {
    iri: `${SCHEMA}givenName`,
    prefixedName: 'schema:givenName',
    label: 'givenName',
    kind: 'property',
    description: 'Given name; first name of a Person',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}familyName`,
    prefixedName: 'schema:familyName',
    label: 'familyName',
    kind: 'property',
    description: 'Family name; last name of a Person',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}jobTitle`,
    prefixedName: 'schema:jobTitle',
    label: 'jobTitle',
    kind: 'property',
    description: 'The job title of the person',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}worksFor`,
    prefixedName: 'schema:worksFor',
    label: 'worksFor',
    kind: 'property',
    description: 'Organizations that the person works for',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}alumniOf`,
    prefixedName: 'schema:alumniOf',
    label: 'alumniOf',
    kind: 'property',
    description: 'An organization that the person is an alumni of',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}knowsAbout`,
    prefixedName: 'schema:knowsAbout',
    label: 'knowsAbout',
    kind: 'property',
    description:
      'Of a Person, and less typically of an Organization, to indicate a topic that is known about',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}knows`,
    prefixedName: 'schema:knows',
    label: 'knows',
    kind: 'property',
    description: 'The most generic bi-directional social/work relation',
    position: 'predicate',
  },
  // Product properties
  {
    iri: `${SCHEMA}brand`,
    prefixedName: 'schema:brand',
    label: 'brand',
    kind: 'property',
    description: 'The brand(s) associated with a product',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}sku`,
    prefixedName: 'schema:sku',
    label: 'sku',
    kind: 'property',
    description: 'The Stock Keeping Unit (SKU), i.e. a merchant-specific identifier for a product',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}mpn`,
    prefixedName: 'schema:mpn',
    label: 'mpn',
    kind: 'property',
    description: 'The Manufacturer Part Number (MPN) of the product',
    position: 'predicate',
  },
  // Opening hours
  {
    iri: `${SCHEMA}openingHoursSpecification`,
    prefixedName: 'schema:openingHoursSpecification',
    label: 'openingHoursSpecification',
    kind: 'property',
    description: 'The opening hours of a place or a certain service inside a place',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}dayOfWeek`,
    prefixedName: 'schema:dayOfWeek',
    label: 'dayOfWeek',
    kind: 'property',
    description: 'The day of the week for which these opening hours are valid',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}opens`,
    prefixedName: 'schema:opens',
    label: 'opens',
    kind: 'property',
    description: 'The opening hour of the place or service on the given day(s)',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}closes`,
    prefixedName: 'schema:closes',
    label: 'closes',
    kind: 'property',
    description: 'The closing hour of the place or service on the given day(s)',
    position: 'predicate',
  },
  {
    iri: `${SCHEMA}priceRange`,
    prefixedName: 'schema:priceRange',
    label: 'priceRange',
    kind: 'property',
    description: 'The price range of the business',
    position: 'predicate',
  },
  // FAQ properties
  {
    iri: `${SCHEMA}acceptedAnswer`,
    prefixedName: 'schema:acceptedAnswer',
    label: 'acceptedAnswer',
    kind: 'property',
    description: 'The answer that has been accepted as best',
    position: 'predicate',
  },
]

// ─── Individuals ──────────────────────────────────────────────────

const SCHEMA_INDIVIDUALS: VocabularyItem[] = [
  {
    iri: `${SCHEMA}InStock`,
    prefixedName: 'schema:InStock',
    label: 'InStock',
    kind: 'individual',
    description: 'Indicates that the item is in stock',
    position: 'object',
  },
  {
    iri: `${SCHEMA}OutOfStock`,
    prefixedName: 'schema:OutOfStock',
    label: 'OutOfStock',
    kind: 'individual',
    description: 'Indicates that the item is out of stock',
    position: 'object',
  },
  {
    iri: `${SCHEMA}PreOrder`,
    prefixedName: 'schema:PreOrder',
    label: 'PreOrder',
    kind: 'individual',
    description: 'Indicates that the item is available for pre-order',
    position: 'object',
  },
  {
    iri: `${SCHEMA}NewCondition`,
    prefixedName: 'schema:NewCondition',
    label: 'NewCondition',
    kind: 'individual',
    description: 'Indicates that the item is new',
    position: 'object',
  },
  {
    iri: `${SCHEMA}UsedCondition`,
    prefixedName: 'schema:UsedCondition',
    label: 'UsedCondition',
    kind: 'individual',
    description: 'Indicates that the item is used',
    position: 'object',
  },
  {
    iri: `${SCHEMA}EventScheduled`,
    prefixedName: 'schema:EventScheduled',
    label: 'EventScheduled',
    kind: 'individual',
    description: 'The event is taking place or has taken place on the startDate as scheduled',
    position: 'object',
  },
  {
    iri: `${SCHEMA}EventCancelled`,
    prefixedName: 'schema:EventCancelled',
    label: 'EventCancelled',
    kind: 'individual',
    description: 'The event has been cancelled',
    position: 'object',
  },
  {
    iri: `${SCHEMA}EventPostponed`,
    prefixedName: 'schema:EventPostponed',
    label: 'EventPostponed',
    kind: 'individual',
    description: 'The event has been postponed and no new date has been set',
    position: 'object',
  },
  {
    iri: `${SCHEMA}OnlineEventAttendanceMode`,
    prefixedName: 'schema:OnlineEventAttendanceMode',
    label: 'OnlineEventAttendanceMode',
    kind: 'individual',
    description: 'MixedEventAttendanceMode: an event that is held both online and offline',
    position: 'object',
  },
  {
    iri: `${SCHEMA}OfflineEventAttendanceMode`,
    prefixedName: 'schema:OfflineEventAttendanceMode',
    label: 'OfflineEventAttendanceMode',
    kind: 'individual',
    description: 'OfflineEventAttendanceMode: an event that is primarily conducted offline',
    position: 'object',
  },
  {
    iri: `${SCHEMA}MixedEventAttendanceMode`,
    prefixedName: 'schema:MixedEventAttendanceMode',
    label: 'MixedEventAttendanceMode',
    kind: 'individual',
    description: 'MixedEventAttendanceMode: an event that is held both online and offline',
    position: 'object',
  },
  {
    iri: `${SCHEMA}Monday`,
    prefixedName: 'schema:Monday',
    label: 'Monday',
    kind: 'individual',
    description: 'The day of the week: Monday',
    position: 'object',
  },
  {
    iri: `${SCHEMA}Tuesday`,
    prefixedName: 'schema:Tuesday',
    label: 'Tuesday',
    kind: 'individual',
    description: 'The day of the week: Tuesday',
    position: 'object',
  },
  {
    iri: `${SCHEMA}Wednesday`,
    prefixedName: 'schema:Wednesday',
    label: 'Wednesday',
    kind: 'individual',
    description: 'The day of the week: Wednesday',
    position: 'object',
  },
  {
    iri: `${SCHEMA}Thursday`,
    prefixedName: 'schema:Thursday',
    label: 'Thursday',
    kind: 'individual',
    description: 'The day of the week: Thursday',
    position: 'object',
  },
  {
    iri: `${SCHEMA}Friday`,
    prefixedName: 'schema:Friday',
    label: 'Friday',
    kind: 'individual',
    description: 'The day of the week: Friday',
    position: 'object',
  },
  {
    iri: `${SCHEMA}Saturday`,
    prefixedName: 'schema:Saturday',
    label: 'Saturday',
    kind: 'individual',
    description: 'The day of the week: Saturday',
    position: 'object',
  },
  {
    iri: `${SCHEMA}Sunday`,
    prefixedName: 'schema:Sunday',
    label: 'Sunday',
    kind: 'individual',
    description: 'The day of the week: Sunday',
    position: 'object',
  },
]

// ─── Combined export ───────────────────────────────────────────────

export const SCHEMAORG_VOCABULARY: VocabularyItem[] = [
  ...SCHEMA_CLASSES,
  ...SCHEMA_PROPERTIES,
  ...SCHEMA_INDIVIDUALS,
]
